# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Lee Cannon <leecannon@leecannon.xyz>

name: CI

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
      - "**.zig.zon"
  pull_request:
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
      - "**.zig.zon"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2

      - name: Lint
        run: zig fmt --check --ast-check .

      - name: Test
        run: zig build test --summary all
